apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hellok8s
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hellok8s
    spec:
      containers:
      - name: hellok8s
        image: andresmamani2018/server-basic:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000