apiVersion: v1
kind: Service
metadata:  
  name: web-nodeport-service
spec:
  selector:    
    component: web
  type: NodePort
  ports:  
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30252
    protocol: TCP